/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RAGChatPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_RAG_CHAT = "rag-chat-view";
var CHUNK_SIZE = 400;
var CHUNK_OVERLAP = 50;
var TOP_K = 5;
var DEFAULT_SETTINGS = {
  provider: "openai",
  baseUrl: "https://api.openai.com",
  apiKey: "",
  model: "gpt-4o",
  temperature: 0.7,
  systemPrompt: "You are a helpful assistant. Answer questions based on the provided context from the user's knowledge base. If the context doesn't contain enough information, say so.",
  consentGiven: false,
  localLlmType: "ollama",
  localLlmUrl: "http://localhost:11434",
  localLlmModel: "llama3"
};
var PROVIDERS = {
  "openai": { url: "https://api.openai.com", model: "gpt-4o", label: "OpenAI", needsKey: true },
  "anthropic": { url: "https://api.anthropic.com", model: "claude-3-5-sonnet-20241022", label: "Anthropic (Claude)", needsKey: true },
  "google": { url: "https://generativelanguage.googleapis.com", model: "gemini-2.0-flash", label: "Google Gemini", needsKey: true },
  "mistral": { url: "https://api.mistral.ai", model: "mistral-large-latest", label: "Mistral", needsKey: true },
  "groq": { url: "https://api.groq.com/openai", model: "llama-3.3-70b-versatile", label: "Groq (fast)", needsKey: true },
  "xai": { url: "https://api.x.ai", model: "grok-2-latest", label: "xAI (Grok)", needsKey: true },
  "deepseek": { url: "https://api.deepseek.com", model: "deepseek-chat", label: "DeepSeek", needsKey: true },
  "cohere": { url: "https://api.cohere.com", model: "command-r-plus-08-2024", label: "Cohere", needsKey: true },
  "together": { url: "https://api.together.xyz", model: "meta-llama/Llama-3-70b-chat-hf", label: "Together AI", needsKey: true },
  "perplexity": { url: "https://api.perplexity.ai", model: "llama-3.1-sonar-large-128k-online", label: "Perplexity", needsKey: true },
  "local": { url: "http://localhost:11434", model: "llama3", label: "Local llm", needsKey: false },
  "custom": { url: "", model: "", label: "Custom (OpenAI-compat)", needsKey: false }
};
var LOCAL_LLM_TYPES = {
  "ollama": { label: "Ollama", defaultUrl: "http://localhost:11434", defaultModel: "llama3", hint: "Run: ollama serve" },
  "llamacpp": { label: "llama.cpp server", defaultUrl: "http://localhost:8080", defaultModel: "local", hint: "Run: ./llama-server -m model.gguf --port 8080" },
  "lmstudio": { label: "LM Studio", defaultUrl: "http://localhost:1234", defaultModel: "local", hint: "Start server in LM Studio app" },
  "jan": { label: "Jan", defaultUrl: "http://localhost:1337", defaultModel: "local", hint: "Start server in Jan app" },
  "openaicompat": { label: "Other (OpenAI-compat)", defaultUrl: "http://localhost:8080", defaultModel: "local", hint: "Any server with /v1/chat/completions" }
};
function tokenize(text) {
  return text.toLowerCase().replace(/[^a-z0-9\s]/g, " ").split(/\s+/).filter((t) => t.length > 2);
}
function termFrequencies(tokens) {
  var _a;
  const tf = {};
  for (const t of tokens)
    tf[t] = ((_a = tf[t]) != null ? _a : 0) + 1;
  const total = tokens.length || 1;
  for (const t in tf)
    tf[t] /= total;
  return tf;
}
function chunkText(text) {
  const words = text.split(/\s+/);
  const chunks = [];
  let i = 0;
  while (i < words.length) {
    chunks.push(words.slice(i, i + CHUNK_SIZE).join(" "));
    i += CHUNK_SIZE - CHUNK_OVERLAP;
  }
  return chunks.filter((c) => c.trim().length > 0);
}
function bm25Score(queryTerms, chunkTerms, chunkLen, avgLen, docFreq, numDocs, k1 = 1.5, b = 0.75) {
  var _a, _b;
  let score = 0;
  for (const term of queryTerms) {
    const tf = (_a = chunkTerms[term]) != null ? _a : 0;
    if (tf === 0)
      continue;
    const df = (_b = docFreq[term]) != null ? _b : 0;
    const idf = Math.log((numDocs - df + 0.5) / (df + 0.5) + 1);
    const tfNorm = tf * (k1 + 1) / (tf + k1 * (1 - b + b * (chunkLen / avgLen)));
    score += idf * tfNorm;
  }
  return score;
}
async function callLLM(settings, messages) {
  const provider = settings.provider;
  const isLocal = provider === "local";
  const baseUrl = isLocal ? settings.localLlmUrl : settings.baseUrl;
  const model = isLocal ? settings.localLlmModel : settings.model;
  const apiKey = settings.apiKey;
  if (provider === "google") {
    const geminiMessages = messages.filter((m) => m.role !== "system").map((m) => ({ role: m.role === "assistant" ? "model" : "user", parts: [{ text: m.content }] }));
    const systemMsg = messages.find((m) => m.role === "system");
    const body = { contents: geminiMessages };
    if (systemMsg)
      body.systemInstruction = { parts: [{ text: systemMsg.content }] };
    const resp2 = await (0, import_obsidian.requestUrl)({
      url: `${baseUrl}/v1beta/models/${model}:generateContent?key=${apiKey}`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
      throw: false
    });
    if (resp2.status >= 400)
      throw new Error(`Gemini error ${resp2.status}: ${resp2.text}`);
    return resp2.json.candidates[0].content.parts[0].text;
  }
  if (provider === "anthropic") {
    const systemMsg = messages.find((m) => m.role === "system");
    const anthropicMessages = messages.filter((m) => m.role !== "system");
    const body = { model, max_tokens: 4096, messages: anthropicMessages };
    if (systemMsg)
      body.system = systemMsg.content;
    const resp2 = await (0, import_obsidian.requestUrl)({
      url: `${baseUrl}/v1/messages`,
      method: "POST",
      headers: { "Content-Type": "application/json", "x-api-key": apiKey, "anthropic-version": "2023-06-01" },
      body: JSON.stringify(body),
      throw: false
    });
    if (resp2.status >= 400)
      throw new Error(`Anthropic error ${resp2.status}: ${resp2.text}`);
    return resp2.json.content[0].text;
  }
  if (isLocal && settings.localLlmType === "ollama") {
    const resp2 = await (0, import_obsidian.requestUrl)({
      url: `${baseUrl}/api/chat`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ model, messages, stream: false }),
      throw: false
    });
    if (resp2.status >= 400)
      throw new Error(`Ollama error ${resp2.status}: ${resp2.text}`);
    return resp2.json.message.content;
  }
  const headers = { "Content-Type": "application/json" };
  if (apiKey)
    headers["Authorization"] = `Bearer ${apiKey}`;
  const resp = await (0, import_obsidian.requestUrl)({
    url: `${baseUrl}/v1/chat/completions`,
    method: "POST",
    headers,
    body: JSON.stringify({ model, messages, temperature: settings.temperature }),
    throw: false
  });
  if (resp.status >= 400)
    throw new Error(`API error ${resp.status}: ${resp.text}`);
  return resp.json.choices[0].message.content;
}
var VaultIndex = class {
  constructor(plugin) {
    this.entries = /* @__PURE__ */ new Map();
    this.docFreq = {};
    this.avgChunkLen = 0;
    this.plugin = plugin;
  }
  async load() {
    try {
      const raw = await this.plugin.loadData();
      if (raw == null ? void 0 : raw.index) {
        for (const e of raw.index)
          this.entries.set(e.path, e);
        this.recomputeStats();
      }
    } catch (e) {
    }
  }
  async save() {
    var _a;
    const existing = (_a = await this.plugin.loadData()) != null ? _a : {};
    await this.plugin.saveData({ ...existing, index: Array.from(this.entries.values()) });
  }
  async indexFile(file) {
    const content = await this.plugin.app.vault.read(file);
    const chunks = chunkText(content).map((text) => ({
      text,
      terms: termFrequencies(tokenize(text))
    }));
    this.entries.set(file.path, { path: file.path, mtime: file.stat.mtime, chunks });
    this.recomputeStats();
  }
  removeFile(path) {
    this.entries.delete(path);
    this.recomputeStats();
  }
  needsReindex(file) {
    const entry = this.entries.get(file.path);
    return !entry || entry.mtime !== file.stat.mtime;
  }
  search(query) {
    const queryTerms = tokenize(query);
    if (queryTerms.length === 0)
      return [];
    const numDocs = this.entries.size;
    const results = [];
    for (const entry of this.entries.values()) {
      let best = 0;
      let bestChunk = "";
      for (const chunk of entry.chunks) {
        const chunkLen = Object.keys(chunk.terms).length || 1;
        const score = bm25Score(queryTerms, chunk.terms, chunkLen, this.avgChunkLen, this.docFreq, numDocs);
        if (score > best) {
          best = score;
          bestChunk = chunk.text;
        }
      }
      if (best > 0)
        results.push({ filePath: entry.path, snippet: bestChunk.slice(0, 300), score: best });
    }
    return results.sort((a, b) => b.score - a.score).slice(0, TOP_K);
  }
  get size() {
    return this.entries.size;
  }
  recomputeStats() {
    var _a;
    this.docFreq = {};
    let totalLen = 0;
    let totalChunks = 0;
    for (const entry of this.entries.values()) {
      const seen = /* @__PURE__ */ new Set();
      for (const chunk of entry.chunks) {
        totalLen += Object.keys(chunk.terms).length;
        totalChunks++;
        for (const term of Object.keys(chunk.terms)) {
          if (!seen.has(term)) {
            this.docFreq[term] = ((_a = this.docFreq[term]) != null ? _a : 0) + 1;
            seen.add(term);
          }
        }
      }
    }
    this.avgChunkLen = totalChunks > 0 ? totalLen / totalChunks : 1;
  }
};
var RAGChatView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.messages = [];
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_RAG_CHAT;
  }
  getDisplayText() {
    return "Chat";
  }
  getIcon() {
    return "message-circle";
  }
  async onOpen() {
    await Promise.resolve();
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("rag-chat-view");
    this.messagesContainer = container.createDiv({ cls: "rag-chat-messages" });
    const inputContainer = container.createDiv({ cls: "rag-chat-input-container" });
    const inputWrapper = inputContainer.createDiv({ cls: "rag-chat-input-wrapper" });
    this.inputEl = inputWrapper.createEl("textarea", {
      cls: "rag-chat-input",
      attr: { placeholder: "Ask a question about your notes...", rows: "1" }
    });
    const sendButton = inputWrapper.createEl("button", { text: "Send", cls: "rag-chat-send-button" });
    this.inputEl.addEventListener("input", () => {
      this.inputEl.setCssProps({ "--rag-input-height": `${Math.min(this.inputEl.scrollHeight, 200)}px` });
      this.inputEl.addClass("rag-chat-input--resized");
    });
    sendButton.addEventListener("click", () => {
      void this.sendMessage();
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        void this.sendMessage();
      }
    });
    this.renderMessages();
  }
  async onClose() {
    return Promise.resolve();
  }
  async sendMessage() {
    const question = this.inputEl.value.trim();
    if (!question)
      return;
    if (!this.plugin.settings.consentGiven) {
      new import_obsidian.Notice("Please enable data consent in settings before chatting");
      return;
    }
    const isLocal = this.plugin.settings.provider === "local";
    const providerInfo = PROVIDERS[this.plugin.settings.provider];
    if (!isLocal && (providerInfo == null ? void 0 : providerInfo.needsKey) && !this.plugin.settings.apiKey) {
      new import_obsidian.Notice("Please configure an API key in settings");
      return;
    }
    this.messages.push({ role: "user", content: question });
    this.renderMessages();
    this.inputEl.value = "";
    this.inputEl.setCssProps({ "--rag-input-height": "auto" });
    this.inputEl.removeClass("rag-chat-input--resized");
    this.messages.push({ role: "assistant", content: "..." });
    this.renderMessages();
    try {
      const results = this.plugin.index.search(question);
      const context = results.length > 0 ? results.map((r, i) => `[${i + 1}] ${r.filePath}
${r.snippet}`).join("\n\n") : "No relevant notes found.";
      const answer = await callLLM(this.plugin.settings, [
        { role: "system", content: `${this.plugin.settings.systemPrompt}

Context from vault:
${context}` },
        { role: "user", content: question }
      ]);
      this.messages.pop();
      this.messages.push({ role: "assistant", content: answer, sources: results });
      this.renderMessages();
    } catch (error) {
      this.messages.pop();
      const msg = error instanceof Error ? error.message : String(error);
      this.messages.push({ role: "assistant", content: `Error: ${msg}` });
      this.renderMessages();
      new import_obsidian.Notice(`Query failed: ${msg}`);
    }
  }
  renderMessages() {
    var _a;
    this.messagesContainer.empty();
    if (this.messages.length === 0) {
      const empty = this.messagesContainer.createDiv({ cls: "rag-chat-empty" });
      empty.createDiv({ cls: "rag-chat-empty-icon", text: "\u{1F4AC}" });
      empty.createDiv({ cls: "rag-chat-empty-title", text: "Start a conversation" });
      empty.createDiv({ cls: "rag-chat-empty-subtitle", text: "Ask questions about your notes and get AI-powered answers with sources." });
      return;
    }
    for (const msg of this.messages) {
      const msgDiv = this.messagesContainer.createDiv({ cls: `rag-chat-message ${msg.role}` });
      msgDiv.createDiv({ cls: "rag-chat-avatar" }).setText(msg.role === "user" ? "\uFFFD\uFFFD" : "\u{1F916}");
      const contentWrapper = msgDiv.createDiv({ cls: "rag-chat-content" });
      const bubble = contentWrapper.createDiv({ cls: "rag-chat-bubble" });
      if (msg.content === "...") {
        const loading = bubble.createDiv({ cls: "rag-chat-loading" });
        for (let i = 0; i < 3; i++)
          loading.createDiv({ cls: "rag-chat-loading-dot" });
      } else {
        void import_obsidian.MarkdownRenderer.renderMarkdown(msg.content, bubble, "", this.plugin);
      }
      if (msg.sources && msg.sources.length > 0) {
        const sourcesDiv = contentWrapper.createDiv({ cls: "rag-chat-sources" });
        sourcesDiv.createDiv({ cls: "rag-chat-source-label", text: "\u{1F4DA} Sources" });
        for (const source of msg.sources) {
          const item = sourcesDiv.createDiv({ cls: "rag-chat-source-item" });
          item.createDiv({ cls: "rag-chat-source-file", text: (_a = source.filePath.split("/").pop()) != null ? _a : source.filePath });
          item.createDiv({ cls: "rag-chat-source-snippet", text: source.snippet });
          item.addEventListener("click", () => {
            void this.openFile(source.filePath);
          });
        }
      }
    }
    this.messagesContainer.scrollTop = this.messagesContainer.scrollHeight;
  }
  async openFile(filePath) {
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (file instanceof import_obsidian.TFile) {
      await this.app.workspace.getLeaf(false).openFile(file);
    } else {
      new import_obsidian.Notice(`File not found: ${filePath}`);
    }
  }
};
var RAGChatPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.debounceTimer = null;
  }
  async onload() {
    await this.loadSettings();
    this.index = new VaultIndex(this);
    await this.index.load();
    this.registerView(VIEW_TYPE_RAG_CHAT, (leaf) => new RAGChatView(leaf, this));
    this.addRibbonIcon("message-circle", "Open chat", () => {
      void this.activateView();
    });
    this.addCommand({ id: "open-view", name: "Open chat view", callback: () => {
      void this.activateView();
    } });
    this.addCommand({ id: "rebuild-index", name: "Rebuild vault index", callback: () => {
      void this.rebuildIndex();
    } });
    this.addSettingTab(new RAGChatSettingTab(this.app, this));
    this.registerEvent(this.app.vault.on("modify", (file) => {
      if (file instanceof import_obsidian.TFile && file.extension === "md")
        this.scheduleIndex(file);
    }));
    this.registerEvent(this.app.vault.on("create", (file) => {
      if (file instanceof import_obsidian.TFile && file.extension === "md")
        this.scheduleIndex(file);
    }));
    this.registerEvent(this.app.vault.on("delete", (file) => {
      if (file instanceof import_obsidian.TFile && file.extension === "md") {
        this.index.removeFile(file.path);
        void this.index.save();
      }
    }));
    this.registerEvent(this.app.vault.on("rename", (file, oldPath) => {
      if (file instanceof import_obsidian.TFile && file.extension === "md") {
        this.index.removeFile(oldPath);
        this.scheduleIndex(file);
      }
    }));
    void this.initialIndex();
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_RAG_CHAT)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        await rightLeaf.setViewState({ type: VIEW_TYPE_RAG_CHAT, active: true });
        leaf = rightLeaf;
      }
    }
    if (leaf)
      workspace.revealLeaf(leaf);
  }
  scheduleIndex(file) {
    if (this.debounceTimer)
      clearTimeout(this.debounceTimer);
    this.debounceTimer = setTimeout(() => {
      void (async () => {
        await this.index.indexFile(file);
        await this.index.save();
      })();
    }, 1e3);
  }
  async initialIndex() {
    const toIndex = this.app.vault.getMarkdownFiles().filter((f) => this.index.needsReindex(f));
    if (toIndex.length === 0)
      return;
    new import_obsidian.Notice(`Building search index for ${toIndex.length} notes...`);
    for (const file of toIndex)
      await this.index.indexFile(file);
    await this.index.save();
    new import_obsidian.Notice(`\u2705 Index ready (${this.index.size} notes)`);
  }
  async rebuildIndex() {
    const mdFiles = this.app.vault.getMarkdownFiles();
    new import_obsidian.Notice(`Rebuilding index for ${mdFiles.length} notes...`);
    for (const file of mdFiles)
      await this.index.indexFile(file);
    await this.index.save();
    new import_obsidian.Notice(`\u2705 Index rebuilt (${mdFiles.length} notes)`);
  }
  async loadSettings() {
    var _a;
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, (_a = data == null ? void 0 : data.settings) != null ? _a : {});
  }
  async saveSettings() {
    var _a;
    const data = (_a = await this.loadData()) != null ? _a : {};
    await this.saveData({ ...data, settings: this.settings });
  }
};
var RAGChatSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Configuration").setHeading();
    new import_obsidian.Setting(containerEl).setName("AI provider").setHeading();
    new import_obsidian.Setting(containerEl).setName("Provider").setDesc("Select the AI provider to use").addDropdown((dropdown) => {
      for (const [key, info] of Object.entries(PROVIDERS))
        dropdown.addOption(key, info.label);
      dropdown.setValue(this.plugin.settings.provider);
      dropdown.onChange(async (value) => {
        this.plugin.settings.provider = value;
        if (value !== "custom" && value !== "local") {
          this.plugin.settings.baseUrl = PROVIDERS[value].url;
          this.plugin.settings.model = PROVIDERS[value].model;
        }
        await this.plugin.saveSettings();
        this.display();
      });
      return dropdown;
    });
    const isLocal = this.plugin.settings.provider === "local";
    const isCustom = this.plugin.settings.provider === "custom";
    const providerInfo = PROVIDERS[this.plugin.settings.provider];
    if (!isLocal) {
      new import_obsidian.Setting(containerEl).setName("Base URL").setDesc("API base URL (auto-filled for known providers)").addText((text) => {
        const t = text.setPlaceholder("https://api.openai.com").setValue(this.plugin.settings.baseUrl).onChange(async (value) => {
          this.plugin.settings.baseUrl = value.trim();
          await this.plugin.saveSettings();
        });
        if (!isCustom)
          t.setDisabled(true);
        return t;
      });
      if (isCustom || (providerInfo == null ? void 0 : providerInfo.needsKey)) {
        new import_obsidian.Setting(containerEl).setName("API key").setDesc("Your API key for the selected provider").addText((text) => {
          text.setPlaceholder("Enter API key").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
            this.plugin.settings.apiKey = value.trim();
            await this.plugin.saveSettings();
          });
          text.inputEl.type = "password";
          return text;
        });
      }
      new import_obsidian.Setting(containerEl).setName("Model").setDesc("Model name (auto-filled, change as needed)").addText((text) => {
        var _a;
        return text.setPlaceholder((_a = providerInfo == null ? void 0 : providerInfo.model) != null ? _a : "model-name").setValue(this.plugin.settings.model).onChange(async (value) => {
          this.plugin.settings.model = value.trim();
          await this.plugin.saveSettings();
        });
      });
    }
    if (isLocal) {
      new import_obsidian.Setting(containerEl).setName("Local model").setHeading();
      new import_obsidian.Setting(containerEl).setName("Local model type").setDesc("Which local server are you running?").addDropdown((dropdown) => {
        for (const [key, info] of Object.entries(LOCAL_LLM_TYPES))
          dropdown.addOption(key, info.label);
        dropdown.setValue(this.plugin.settings.localLlmType);
        dropdown.onChange(async (value) => {
          this.plugin.settings.localLlmType = value;
          this.plugin.settings.localLlmUrl = LOCAL_LLM_TYPES[value].defaultUrl;
          this.plugin.settings.localLlmModel = LOCAL_LLM_TYPES[value].defaultModel;
          await this.plugin.saveSettings();
          this.display();
        });
        return dropdown;
      });
      const localInfo = LOCAL_LLM_TYPES[this.plugin.settings.localLlmType];
      if (localInfo)
        new import_obsidian.Setting(containerEl).setName("Setup hint").setDesc(`\u{1F4A1} ${localInfo.hint}`);
      new import_obsidian.Setting(containerEl).setName("Local server address").setDesc("Full URL including port").addText((text) => {
        var _a;
        return text.setPlaceholder((_a = localInfo == null ? void 0 : localInfo.defaultUrl) != null ? _a : "http://localhost:11434").setValue(this.plugin.settings.localLlmUrl).onChange(async (value) => {
          this.plugin.settings.localLlmUrl = value.trim();
          await this.plugin.saveSettings();
        });
      });
      new import_obsidian.Setting(containerEl).setName("Model name").setDesc("Model to use (e.g., llama3, mistral, phi3)").addText((text) => {
        var _a;
        return text.setPlaceholder((_a = localInfo == null ? void 0 : localInfo.defaultModel) != null ? _a : "llama3").setValue(this.plugin.settings.localLlmModel).onChange(async (value) => {
          this.plugin.settings.localLlmModel = value.trim();
          await this.plugin.saveSettings();
        });
      });
      new import_obsidian.Setting(containerEl).setName("Test local model").setDesc("Check if the local server is reachable").addButton((button) => button.setButtonText("Test").onClick(async () => {
        var _a, _b;
        button.setDisabled(true);
        const url = this.plugin.settings.localLlmUrl;
        const hint = (_b = (_a = LOCAL_LLM_TYPES[this.plugin.settings.localLlmType]) == null ? void 0 : _a.hint) != null ? _b : "";
        try {
          let reachable = false;
          for (const ep of ["/api/tags", "/v1/models", "/health"]) {
            try {
              const r = await (0, import_obsidian.requestUrl)({ url: url + ep, throw: false });
              if (r.status < 500) {
                reachable = true;
                break;
              }
            } catch (e) {
            }
          }
          new import_obsidian.Notice(reachable ? `\u2705 Local LLM reachable at ${url}` : `\u274C Not responding at ${url}

${hint}`);
        } catch (e) {
          new import_obsidian.Notice(`\u274C Cannot reach ${url}`);
        } finally {
          button.setDisabled(false);
        }
      }));
    }
    new import_obsidian.Setting(containerEl).setName("Temperature").setDesc("Controls randomness: 0 = focused, 1 = creative").addSlider((slider) => slider.setLimits(0, 1, 0.1).setValue(this.plugin.settings.temperature).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.temperature = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("System prompt").setDesc("Instructions for the AI assistant").addTextArea((text) => {
      text.setPlaceholder("You are a helpful assistant...").setValue(this.plugin.settings.systemPrompt).onChange(async (value) => {
        this.plugin.settings.systemPrompt = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 4;
      return text;
    });
    new import_obsidian.Setting(containerEl).setName("Data consent").setDesc("I understand my vault content may be sent to external providers").addToggle((toggle) => toggle.setValue(this.plugin.settings.consentGiven).onChange(async (value) => {
      this.plugin.settings.consentGiven = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Rebuild index").setDesc("Re-index all notes in your vault (safe to run at any time)").addButton((button) => button.setButtonText("Rebuild").onClick(async () => {
      button.setDisabled(true);
      button.setButtonText("Rebuilding...");
      await this.plugin.rebuildIndex();
      button.setDisabled(false);
      button.setButtonText("Rebuild");
      this.display();
    }));
  }
};
